apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend
          image: rauqoz/pbackgcp:lastest
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: credentials
                key: gcp-dsu.json
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
          - name: MYSQL_HOST 
            value: 
          - name: MYSQL_USER 
            value: 
          - name: MYSQL_PASSWORD 
            value: 
          - name: MYSQL_DATABASE 
            value: 
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  labels:
    app: backend-deployment
spec:
  type: LoadBalancer
  selector:
    app: backend-deployment
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP