const config = {
    CLOUD_FUNCTION_USER: process.env.REACT_APP_CLOUDFUNCTION_USER_URL,
    CLOUD_FUNCTION_ALBUMSPHOTOS: process.env.REACT_APP_CLOUDFUNCTION_ALBUMSPHOTOS_URL,
    MAINFRONTEND_URL: process.env.REACT_APP_MAINFRONTEND_URL
}

module.exports = config;