const config = {
    CLOUD_FUNCTION_USER: process.env.REACT_APP_CLOUDFUNCTION_USER_URL,
    CLOUD_FUNCTION_ALBUMSPHOTOS: process.env.REACT_APP_CLOUDFUNCTION_ALBUMSPHOTOS_URL,
    MAINFRONTEND_URL: process.env.REACT_APP_MAINFRONTEND_URL,
    BACKEND: process.env.REACT_APP_BACKEND_URL,
    CLOUD_FUNCTION_PASSWORD: process.env.REACT_APP_CF_PASSWORD_URL,
    CLOUD_FUNCTION_UPDATE: process.env.REACT_APP_CF_UPDATE_URL
}

module.exports = config;